### ISSUE TITLE
Bug:  Crash after adding .tiff image

### ISSUE THREAD

**Issue by dopeoid** [IvanKosik/vision#1]
the program terminates after adding a .tiff image of size 23000*47000 weighing 470 megabytes with the following error:

cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:79: error: (-215:Assertion failed) pixels <= CV_IO_MAX_IMAGE_PIXELS in function 'cv::validateInputImageSize'

Located in \src\bsmu\vision\plugins\loaders\image\simple.py,  line 42
pixels = cv.imdecode(np.fromfile(path, dtype=np.uint8), cv.IMREAD_UNCHANGED)

**Comment by IvanKosik** [comment]
Fixed in the #3. Now that value can be changed using opencv_io_max_image_pixels config variable.
